#!/bin/sh
# Effort:
# Force an LP10 comparison unit into a direct hardware audio path so its output
# can be compared without vendor pipelines, ALSA software mixing, resampling,
# DSP, software volume, gain, or format conversion. The script backs up the
# current ALSA configuration, stops/kills known audio services, writes a strict
# `type hw` /etc/asound.conf, removes user ALSA overrides, and verifies that no
# known software-processing markers remain in the active ALSA config.
set -eu

MODE="${1:-force}"
STATE_DIR="${LP10_DIRECT_STATE_DIR:-/opt/lp10-direct-audio}"
BACKUP_ROOT="$STATE_DIR/backups"
ALSA_DEVICE="${LP10_DIRECT_ALSA_DEVICE:-hw:0,1}"
PCM_FORMAT="${LP10_DIRECT_PCM_FORMAT:-S16_LE}"
PCM_RATE="${LP10_DIRECT_PCM_RATE:-48000}"
PCM_CHANNELS="${LP10_DIRECT_PCM_CHANNELS:-2}"
KILL_PATTERNS="${LP10_DIRECT_KILL_PATTERNS:-airplaydemo|qobuzConnect|tidalConnect|libreraat|dmr|bluealsa|bluetoothd|gst-launch-1.0|aplay|lp10-netaudio}"
INIT_STOPS="${LP10_DIRECT_INIT_STOPS:-/etc/init.d/S99airplay_v2 /etc/init.d/S95lp10-netaudio /etc/init.d/S99lp10-netaudio}"
FORBIDDEN_ALSA_PATTERN='plug|dmix|dsnoop|softvol|route|rate|samplerate|resample|lavrate|speexrate|linear|ladspa|equal|compressor|limiter|volume|gain|normalize'
LATEST_FILE="$STATE_DIR/latest-backup"

log() {
    printf '%s %s\n' "$(date -Iseconds 2>/dev/null || date)" "$*"
}

die() {
    log "ERROR: $*"
    exit 1
}

card_from_hw() {
    printf '%s\n' "$ALSA_DEVICE" | sed -n 's/^hw:\([0-9][0-9]*\),\([0-9][0-9]*\)$/\1/p'
}

device_from_hw() {
    printf '%s\n' "$ALSA_DEVICE" | sed -n 's/^hw:\([0-9][0-9]*\),\([0-9][0-9]*\)$/\2/p'
}

require_hw_device() {
    case "$ALSA_DEVICE" in
        hw:[0-9]*,[0-9]*)
            ;;
        *)
            die "LP10_DIRECT_ALSA_DEVICE must be an exact hardware endpoint like hw:0,1"
            ;;
    esac
    card="$(card_from_hw)"
    device="$(device_from_hw)"
    [ -n "$card" ] && [ -n "$device" ] || die "could not parse ALSA device $ALSA_DEVICE"
}

remount_rw() {
    mount -o remount,rw / >/dev/null 2>&1 || true
    mount -o remount,rw /etc >/dev/null 2>&1 || true
    mount -o remount,rw /root >/dev/null 2>&1 || true
    mount -o remount,rw /opt >/dev/null 2>&1 || true
}

backup_file() {
    source="$1"
    backup_dir="$2"
    if [ -e "$source" ]; then
        safe="$(printf '%s\n' "$source" | sed 's#^/##; s#/#__#g')"
        cp "$source" "$backup_dir/$safe"
        log "backed up $source -> $backup_dir/$safe"
    fi
}

restore_file() {
    target="$1"
    backup_dir="$2"
    safe="$(printf '%s\n' "$target" | sed 's#^/##; s#/#__#g')"
    if [ -e "$backup_dir/$safe" ]; then
        cp "$backup_dir/$safe" "$target"
        log "restored $target"
    else
        rm -f "$target"
        log "removed $target because no original backup existed"
    fi
}

release_audio_pipelines() {
    log "releasing vendor audio pipelines"
    for init_script in $INIT_STOPS; do
        if [ -x "$init_script" ]; then
            log "stopping $init_script"
            "$init_script" stop >/dev/null 2>&1 || true
        fi
    done

    ps 2>/dev/null | grep -E "$KILL_PATTERNS" | grep -v grep | while IFS= read -r line; do
        pid=""
        for field in $line; do
            case "$field" in
                *[!0-9]*)
                    ;;
                *)
                    pid="$field"
                    break
                    ;;
            esac
        done
        case "$pid" in
            ''|*[!0-9]*|"$$")
                ;;
            *)
                log "terminating audio process pid=$pid: $line"
                kill "$pid" 2>/dev/null || true
                ;;
        esac
    done
}

force_kill_audio_pipelines() {
    release_audio_pipelines
    sleep 1
    ps 2>/dev/null | grep -E "$KILL_PATTERNS" | grep -v grep | while IFS= read -r line; do
        pid=""
        for field in $line; do
            case "$field" in
                *[!0-9]*)
                    ;;
                *)
                    pid="$field"
                    break
                    ;;
            esac
        done
        case "$pid" in
            ''|*[!0-9]*|"$$")
                ;;
            *)
                log "force killing audio process pid=$pid: $line"
                kill -9 "$pid" 2>/dev/null || true
                ;;
        esac
    done
}

write_direct_asound_conf() {
    card="$1"
    device="$2"
    cat > /etc/asound.conf <<EOF
# Generated by lp10-force-direct-audio.sh.
# Purpose: force the LP10 comparison unit to use the hardware ALSA path directly.
# No plug, dmix, dsnoop, softvol, route, rate, DSP, or software-volume PCM is defined here.

pcm.!default {
    type hw
    card $card
    device $device
}

ctl.!default {
    type hw
    card $card
}

pcm.lp10_direct {
    type hw
    card $card
    device $device
}

ctl.lp10_direct {
    type hw
    card $card
}
EOF
    rm -f /root/.asoundrc /etc/asoundrc
    log "installed direct ALSA config: default -> $ALSA_DEVICE"
}

verify_direct_mode() {
    [ -r /etc/asound.conf ] || die "/etc/asound.conf was not written"
    grep -q "type hw" /etc/asound.conf || die "/etc/asound.conf does not contain type hw"
    grep -q "card $(card_from_hw)" /etc/asound.conf || die "/etc/asound.conf does not target card $(card_from_hw)"
    grep -q "device $(device_from_hw)" /etc/asound.conf || die "/etc/asound.conf does not target device $(device_from_hw)"
    if grep -vi '^[[:space:]]*#' /etc/asound.conf | grep -Eiq "$FORBIDDEN_ALSA_PATTERN"; then
        die "/etc/asound.conf still contains forbidden conversion/mixer terms"
    fi
    [ ! -e /etc/asoundrc ] || die "/etc/asoundrc still exists"
    [ ! -e /root/.asoundrc ] || die "/root/.asoundrc still exists"
    log "verified direct ALSA config: no plug/dmix/softvol/rate/DSP markers"
}

write_direct_env() {
    mkdir -p "$STATE_DIR"
    cat > "$STATE_DIR/direct-env.sh" <<EOF
export LP10_DIRECT_ALSA_DEVICE='$ALSA_DEVICE'
export LP10_DIRECT_PCM_FORMAT='$PCM_FORMAT'
export LP10_DIRECT_PCM_RATE='$PCM_RATE'
export LP10_DIRECT_PCM_CHANNELS='$PCM_CHANNELS'
EOF
    log "wrote $STATE_DIR/direct-env.sh"
}

apply_direct_mode() {
    require_hw_device
    remount_rw
    mkdir -p "$BACKUP_ROOT"
    backup_dir="$BACKUP_ROOT/$(date +%Y%m%d-%H%M%S 2>/dev/null || date +%s)"
    mkdir -p "$backup_dir"
    backup_file /etc/asound.conf "$backup_dir"
    backup_file /etc/asoundrc "$backup_dir"
    backup_file /root/.asoundrc "$backup_dir"
    printf '%s\n' "$backup_dir" > "$LATEST_FILE"

    release_audio_pipelines
    write_direct_asound_conf "$(card_from_hw)" "$(device_from_hw)"
    write_direct_env
    verify_direct_mode

    log "direct mode active"
    log "raw playback command for comparison:"
    log "aplay -q -D $ALSA_DEVICE -c $PCM_CHANNELS -r $PCM_RATE -f $PCM_FORMAT -t raw <file.raw>"
}

force_direct_mode() {
    require_hw_device
    remount_rw
    mkdir -p "$BACKUP_ROOT"
    backup_dir="$BACKUP_ROOT/force-$(date +%Y%m%d-%H%M%S 2>/dev/null || date +%s)"
    mkdir -p "$backup_dir"
    backup_file /etc/asound.conf "$backup_dir"
    backup_file /etc/asoundrc "$backup_dir"
    backup_file /root/.asoundrc "$backup_dir"
    printf '%s\n' "$backup_dir" > "$LATEST_FILE"

    force_kill_audio_pipelines
    write_direct_asound_conf "$(card_from_hw)" "$(device_from_hw)"
    write_direct_env
    verify_direct_mode

    if command -v sync >/dev/null 2>&1; then
        sync || true
    fi
    log "FORCE direct mode active"
    log "only direct raw playback should be used:"
    log "aplay -q -D $ALSA_DEVICE -c $PCM_CHANNELS -r $PCM_RATE -f $PCM_FORMAT -t raw <file.raw>"
}

restore_direct_mode() {
    [ -r "$LATEST_FILE" ] || die "no backup marker found at $LATEST_FILE"
    backup_dir="$(cat "$LATEST_FILE")"
    [ -d "$backup_dir" ] || die "backup directory not found: $backup_dir"
    remount_rw
    force_kill_audio_pipelines
    restore_file /etc/asound.conf "$backup_dir"
    restore_file /etc/asoundrc "$backup_dir"
    restore_file /root/.asoundrc "$backup_dir"
    log "restore complete from $backup_dir"
}

status_direct_mode() {
    log "direct target: $ALSA_DEVICE $PCM_FORMAT $PCM_RATE Hz $PCM_CHANNELS channels"
    if [ -r /etc/asound.conf ]; then
        log "/etc/asound.conf:"
        sed -n '1,180p' /etc/asound.conf
    else
        log "/etc/asound.conf missing"
    fi
    log "audio processes:"
    ps 2>/dev/null | grep -E "$KILL_PATTERNS|audio|alsa|gst|cast|roon|tidal|qobuz|airplay" | grep -v grep || true
    if command -v lsof >/dev/null 2>&1; then
        log "open sound devices:"
        lsof /dev/snd/* 2>/dev/null || true
    fi
}

case "$MODE" in
    force)
        force_direct_mode
        ;;
    apply)
        apply_direct_mode
        ;;
    release)
        release_audio_pipelines
        ;;
    restore)
        restore_direct_mode
        ;;
    status)
        status_direct_mode
        ;;
    *)
        printf 'usage: %s [force|apply|release|restore|status]\n' "$0" >&2
        exit 2
        ;;
esac
